local async = require('sapho.async')
local function wait(task)
  assert.is_true(vim.wait(1000, function() return task.done end))
end

describe('sapho.async', function()
  it('handles synchronous callbacks without yielding', function()
    local value
    local task = async.run(function()
      value = async.await(function(cb) cb(nil, 'ok') end)
    end)
    wait(task)
    assert.is_nil(value)
    local a, b
    wait(async.run(function() a, b = async.await(function(cb) cb(nil, 'ok') end) end))
    assert.is_nil(a); assert.are.equal('ok', b)
  end)
  it('resumes asynchronous callbacks', function()
    local cb, value
    local task = async.run(function() value = async.await(function(callback) cb = callback end) end)
    assert.is_false(task.done)
    cb(42)
    wait(task)
    assert.are.equal(42, value)
  end)
  it('schedules resumption from fast events', function()
    local safe
    local task = async.run(function()
      async.sleep(1)
      safe = not vim.in_fast_event()
    end)
    wait(task)
    assert.is_true(safe)
  end)
  it('ignores double callbacks', function()
    local cb, count = nil, 0
    local task = async.run(function()
      async.await(function(callback) cb = callback end)
      count = count + 1
    end)
    cb(); cb(); wait(task)
    assert.are.equal(1, count)
  end)
  it('preserves nil varargs', function()
    local n, a, b, c
    wait(async.run(function()
      local function check(...) n, a, b, c = select('#', ...), ... end
      check(async.await(function(cb) cb(nil, 'err', nil) end))
    end))
    assert.are.equal(3, n); assert.is_nil(a); assert.are.equal('err', b); assert.is_nil(c)
  end)
  it('reports task errors with tracebacks', function()
    local a, err
    wait(async.run(function() error('boom') end, function(x, e) a, err = x, e end))
    assert.is_nil(a); assert.matches('boom', err); assert.matches('stack traceback', err)
  end)
  it('rejects await outside run', function()
    assert.has_error(function() async.await(function() end) end, 'sapho: await requires async.run coroutine')
  end)
  it('starts nested runs independently', function()
    local child, cb
    local parent = async.run(function()
      child = async.run(function() async.await(function(callback) cb = callback end) end)
    end)
    wait(parent); assert.is_false(child.done)
    cb(); wait(child)
  end)
  it('wraps vim.system and leaves fast event context', function()
    local result, safe
    local system = async.wrap(function(cmd, cb) vim.system(cmd, {}, cb) end, 1)
    wait(async.run(function()
      result = system({ 'echo', 'hi' })
      safe = not vim.in_fast_event()
    end))
    assert.matches('hi', result.stdout); assert.is_true(safe)
  end)
  it('cancels during sleep without continuing', function()
    local continued, a, err = false
    local task = async.run(function() async.sleep(5); continued = true end,
      function(x, e) a, err = x, e end)
    task.cancel()
    wait(task)
    assert.is_nil(a); assert.are.equal('cancelled', err); assert.is_false(continued)
  end)
  it('schedule leaves fast context', function()
    local safe
    wait(async.run(function() async.schedule(); safe = not vim.in_fast_event() end))
    assert.is_true(safe)
  end)
end)
