local config = require('sapho.config')
describe('sapho reading configuration', function()
  after_each(function() config.setup({}) end)
  it('has no forced mapping or edit review option', function()
    assert.is_nil(config.setup({}).keymap)
    assert.is_nil(config.get().edit_review)
    assert.are.equal('<leader>sa', config.setup({ keymap = '<leader>sa' }).keymap)
    assert.is_nil(config.setup({}).selection_ask)
  end)
  it('validates provider and layout options', function()
    assert.has_error(function() config.setup({ effort = 'unknown' }) end)
    assert.are.equal(0, config.setup({}).ui.height) -- automatic 80% screen height
    assert.are.equal(24, config.setup({ ui = { height = 24 } }).ui.height)
    assert.has_error(function() config.setup({ ui = { width = 0 } }) end)
    assert.has_error(function() config.setup({ ui = { height = -1 } }) end)
  end)
end)
